apiVersion: v1
kind: Pod
metadata:
  name: my-web-app

spec:
  containers:
    - name: my-nginx-app
      image: 30206188800434/nginx-os
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
